Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  WebsiteBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${Env}-${App}-web-hosting"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

#  WebsiteBucketPolicy:
#    Type: "AWS::S3::BucketPolicy"
#    Properties:
#      Bucket: !Ref WebsiteBucket
#      PolicyDocument:
#        Version: '2012-10-17'
#        Id: GObjPolicy
#        Statement:
#          - Sid: GetObj
#            Effect: Allow
#            Principal: "*"
#            Action: s3:GetObject
#            Resource: !Sub "arn:aws:s3:::${Env}-${App}-web-hosting/*"

  WebsiteDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteBucket.DomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
        HttpVersion: http2